### PR TITLE
Priestley Taylor 

### PR DESCRIPTION
**Pull request by cpearson1**
Added Priestley Taylor option (etw)
Assumes constant alpha = 1.26
Calculations outlined here: 
https://wetlandscapes.github.io/blog/blog/penman-monteith-and-priestley-taylor/

### CODE REVIEW

**Comment by cgmorton** [comment]
Would you mind closing this pull request and opening a new one against the openet-refet-gee repository and not the cgmorton one?

**Comment by cgmorton** [comment]
Actually, I'm just going to close this and try deleting the original one.  Hopefully that works!

**Comment by cpearson1** [comment]
Is this not merging to Open-ET/openet-refet-gee?

I created a bad one yesterday that merged to cgmorton, but closed it and created this one...

**Comment by cgmorton** [comment]
Your right!  I had opened that one yesterday and didn't catch the change.

**Pull request merged**
